[package]
name = "adn-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "adn"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
indicatif = { workspace = true }
tabled = { workspace = true }
serde_json = { workspace = true }

adn-core = { path = "../core" }
adn-simulation = { path = "../simulation" }
